#!/bin/bash

set -uo pipefail

# Configure system locale to en_US.UTF-8
sed -i 's/#\(en_US.UTF-8 UTF-8\)/\1/g' /etc/locale.gen
locale-gen
echo 'LANG=en_US.UTF-8' > /etc/locale.conf

# Fix Pacman.conf
rm -f /etc/pacman.conf
curl https://raw.githubusercontent.com/parchlinux-ports/Parchlinuxarm-images/main/examples/pacman.conf.example >> /etc/pacman.conf

# Enable Sudo
sudo sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers

# Fix sddm Theming

mkdir -p /etc/sddm.conf.d/
curl https://raw.githubusercontent.com/parchlinux/parch-iso-plasma/main/iso/airootfs/etc/sddm.conf.d/kde_settings.conf >> /etc/sddm.conf.d/kde_settings.conf

# Install Desktop and Apps
packages=(
  bluedevil
  breeze
  breeze-gtk
  breeze-plymouth
  drkonqi
  kactivitymanagerd
  kde-cli-tools
  kde-gtk-config
  kdecoration
  kdeplasma-addons
  kgamma
  kglobalacceld
  kinfocenter
  kmenuedit
  kpipewire
  krdp
  kscreen
  kscreenlocker
  ksshaskpass
  ksystemstats
  kwallet-pam
  kwayland
  kwin
  kwrited
  layer-shell-qt
  libkscreen
  libksysguard
  libplasma
  milou
  ocean-sound-theme
  plasma-activities
  plasma-activities-stats
  plasma-browser-integration
  plasma-desktop
  plasma-disks
  plasma-firewall
  plasma-integration
  plasma-nm
  plasma-pa
  plasma-sdk
  plasma-systemmonitor
  plasma-thunderbolt
  plasma-vault
  plasma-workspace
  plasma-workspace-wallpapers
  plasma5support
  plymouth-kcm
  polkit-kde-agent
  powerdevil
  print-manager
  qqc2-breeze-style
  sddm-kcm
  systemsettings
  wacomtablet
  xdg-desktop-portal-kde
  dolphin
  konsole
  kate
  gwenview
  okular
  parch-zram
  sddm
  parch-branding
  noto-fonts
  vazirmatn-fonts
  parch-emoji-ios
  arch-install-scripts
  avahi
  curl
  git
  btop
  man-db
  neovim
  pacman-contrib
  yay-bin
  python
  rsync
  sudo
  tree
  fastfetch
  neofetch-git
  networkmanager
  network-manager-applet
  zsh
  vim
  pipewire
  pipewire-pulse
  bluez
  bluez-utils
  pipewire-alsa
  wireplumber
)
pacman -Syu --noconfirm --needed "${packages[@]}"

# Enable services
systemctl enable avahi-daemon NetworkManager
systemctl enable sddm
systemctl enable bluetooth
systemctl enable parch-zram


# Prepare system for containers (e.g. for use with K3s)
# https://github.com/k3s-io/k3s/issues/2067#issuecomment-664048424
#if ! grep -q cgroup /boot/cmdline.txt; then
#  sed -i '$ s/$/ cgroup_memory=1 cgroup_enable=memory/g' /boot/cmdline.txt
#fi
