#!/bin/bash

set -uo pipefail

# Replace default kernel + U-Boot with Raspberry Pi foundation's kernel + bootloader
# See https://github.com/fwcd/archlinuxarm-images/issues/3
pacman -R --noconfirm linux-aarch64 uboot-raspberrypi
pacman -Syu --noconfirm --needed linux-rpi raspberrypi-bootloader raspberrypi-utils 

mkdir -p /etc/X11/xorg.conf.d/
curl https://raw.githubusercontent.com/Parchlinux-Ports/rpi-xorg-config/main/etc/X11/xorg.conf.d/99-vc4.conf >> /etc/X11/xorg.conf.d/99-vc4.conf
