#!/bin/bash

set -uo pipefail

# Configure system locale to en_US.UTF-8
sed -i 's/#\(en_US.UTF-8 UTF-8\)/\1/g' /etc/locale.gen
locale-gen
echo 'LANG=en_US.UTF-8' > /etc/locale.conf


# Fix Pacman.conf
rm -f /etc/pacman.conf
curl https://raw.githubusercontent.com/parchlinux-ports/Parchlinuxarm-images/main/examples/pacman.conf.example >> /etc/pacman.conf

# Enable Sudo
sudo sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers

pacman-key --recv-keys 0x8685AD8B

# Add archsink repo
cat <<EOF >> /etc/pacman.conf

[trinity]
Server = https://mirror.ppa.trinitydesktop.org/trinity/archlinux/\$arch
SigLevel = Never

EOF

# Enable parallel downloads
sed -i 's/#\(ParallelDownloads \)/\1/g' /etc/pacman.conf

# Install useful packages
packages=(
  parch-branding
  vazirmatn-fonts
  parch-emoji-ios
  arch-install-scripts
  avahi
  curl
  git
  htop
  btop
  iwd
  man-db
  neovim
  pacman-contrib
  paru-bin
  python
  rsync
  sudo
  tmux
  tree
  neofetch-git
  zsh
  vim
  tde-tdebase
  sddm
  networkmanager
  network-manager-applet
  fastfetch
  pipewire
  pipewire-pulse
  pipewire-alsa
  wireplumber
  bluez
  bluez-utils
)
pacman -Syu --noconfirm --needed "${packages[@]}"

# Enable services
systemctl enable avahi-daemon NetworkManager
systemctl enable sddm
systemctl enable bluetooth
# Prepare system for containers (e.g. for use with K3s)
# https://github.com/k3s-io/k3s/issues/2067#issuecomment-664048424
#if ! grep -q cgroup /boot/cmdline.txt; then
#  sed -i '$ s/$/ cgroup_memory=1 cgroup_enable=memory/g' /boot/cmdline.txt
#fi
